### ISSUE TITLE
Rotating the entire view / grid

### ISSUE THREAD

**Issue by InDieTasten** [hovgaardgames/isodom.js#13]
- [ ] Adjust/design interface
- [ ] Break down into smaller issues
- [ ] Add documentation
- [ ] Add/Adjust example in demo
