### ISSUE TITLE
Custom DOM Nodes as entities

### ISSUE THREAD

**Issue by InDieTasten** [hovgaardgames/isodom.js#14]
- [ ] Adjust/design interface
- [ ] Break down into smaller issues
- [ ] Add documentation
- [ ] Add/Adjust example in demo
